version: '3.3'

services:
  db:
    container_name: ecommerce_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ecommerce
      MYSQL_DATABASE: apis
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
